# Generated by Django 3.2.13 on 2022-05-28 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProFit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Maintenance_type', models.CharField(choices=[('Correctivo', 'Correctivo'), ('Preventivo', 'Preventivo'), ('Revestimientos y Pintura', 'Revestimientos y Pintura'), ('Sistema de emergencia', 'Sistema de emergencia'), ('Remodelación', 'Remodelación'), ('Refacción', 'Refacción')], max_length=500, null=True, verbose_name='Maintenance Type')),
                ('activity', models.CharField(choices=[('Albañilería', 'Albañilería'), ('Plomería', 'Plomería'), ('Electricidad', 'Electricidad'), ('Hidráulica', 'Hidráulica'), ('Electromecánica', 'Electromecánica'), ('Luminaria', 'Luminaria'), ('Limpieza y Desinfección', 'Limpieza y Desinfección')], max_length=500, null=True, verbose_name='Activity')),
                ('Maintenance_Zone', models.CharField(choices=[('Bombas de agua', 'Bombas de agua'), ('Calderos', 'Calderos'), ('Generadores Eléctricos', 'Generadores Eléctricos'), ('Ingresos', 'Ingresos'), ('Parqueaderos', 'Parqueaderos'), ('Ascensores', 'Ascensores'), ('Area comunal', 'Area Comunal'), ('Departamento particular', 'Departamento particular'), ('Terraza', 'Terraza')], max_length=500, null=True, verbose_name='Maintenance Zone')),
                ('Description', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de solicitud')),
            ],
            options={
                'verbose_name': 'Solicitud de Contizacion ProFit',
                'verbose_name_plural': 'Solicitudes de Cotizaciones ProFits',
                'ordering': ('-activity',),
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
            ],
        ),
    ]
