# Generated by Django 3.2.13 on 2022-06-02 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edificio_1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='Units',
            field=models.CharField(choices=[('mL', 'ml'), ('m^2', 'm^2'), ('Kg', 'Kg'), ('Gl', 'Gl')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='item',
            field=models.ForeignKey(max_length=200, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_name_2', to='edificio_1.diagnostico'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='project_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project', to='edificio_1.diagnostico'),
        ),
    ]
