# Generated by Django 3.2.13 on 2022-06-02 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edificio_1', '0002_auto_20220602_0257'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='description',
            field=models.CharField(blank=True, max_length=1000000, null=True),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='available',
            field=models.BooleanField(default=True, verbose_name='Disponible'),
        ),
    ]
