# Generated by Django 3.2.13 on 2022-06-02 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edificio_1', '0003_auto_20220602_0311'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='quantity',
            field=models.PositiveIntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='item',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
