# Generated by Django 3.2.13 on 2022-05-26 21:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Check_Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre_banco', models.CharField(choices=[('Banco del Pichincha', 'Banco del Pichincha'), ('Banco del Pacifico', 'Banco del Pacifico'), ('Banco del Austro', 'Banco del Austro'), ('Produbanco', 'Produbanco'), ('Mutialista Pichincha', 'Mutualista Pichincha'), ('Banco Internacional', 'Banco Internacional'), ('Banco de Guayaquil', 'Banco de Guayaquil'), ('Banco  Bolivariano', 'Banco Bolivariano')], db_index=True, max_length=200, null=True, verbose_name='Nombre de entidad bancaria')),
                ('Numero_de_control', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100000000)], verbose_name='Numero de Control')),
                ('Numero_de_cheque', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10000000)], verbose_name='Numero de Cheque')),
                ('fecha_de_emision', models.DateTimeField(verbose_name='Fecha de emisón')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Valor inscripto')),
                ('direccion_de_retiro', models.CharField(max_length=200, null=True, verbose_name='Dirección de retiro')),
            ],
            options={
                'verbose_name': 'Pago con chequera',
                'verbose_name_plural': 'Pagos con chequera',
                'ordering': ('-fecha_de_emision',),
            },
        ),
        migrations.CreateModel(
            name='Trans_Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transferencia', models.FileField(upload_to='documents/%Y/%m/%d')),
            ],
            options={
                'verbose_name': 'Pagos de Trasferencia',
                'verbose_name_plural': 'Pagos de Trasferencia',
            },
        ),
    ]
