# Generated by Django 3.1.5 on 2021-02-05 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Check_Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre_banco', models.CharField(choices=[('Banco del Pichincha', 'Banco del Pichincha'), ('Banco del Pacifico', 'Banco del Pacifico'), ('Banco del Austro', 'Banco del Austro'), ('Produbanco', 'Produbanco'), ('Mutialista Pichincha', 'Mutualista Pichincha'), ('Banco Internacional', 'Banco Internacional'), ('Banco de Guayaquil', 'Banco de Guayaquil'), ('Banco  Bolivariano', 'Banco Bolivariano')], db_index=True, max_length=200, null=True, verbose_name='Nombre de entidad bancaria')),
                ('numero_de_control', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Número de control')),
                ('numero_de_chueque', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Número de chueque')),
                ('fecha_de_emision', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de emisón')),
                ('direccion_de_retiro', models.CharField(max_length=200, null=True, verbose_name='Dirección de retiro')),
            ],
            options={
                'verbose_name': 'Pago con chequera',
                'verbose_name_plural': 'Pagos con chequera',
            },
        ),
    ]
