# Generated by Django 3.1.5 on 2021-02-05 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='check_payment',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Valor inscripto'),
        ),
    ]
