# Generated by Django 3.1.5 on 2021-02-05 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_check_payment_valor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='check_payment',
            name='numero_de_chueque',
        ),
        migrations.RemoveField(
            model_name='check_payment',
            name='numero_de_control',
        ),
    ]
