# Generated by Django 3.1.5 on 2021-02-05 12:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_auto_20210205_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='check_payment',
            name='Numero_de_cheque',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(7)], verbose_name='Numero de Cheque'),
        ),
        migrations.AddField(
            model_name='check_payment',
            name='Numero_de_control',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Numero de Control'),
        ),
    ]
