# Generated by Django 3.1.5 on 2021-03-20 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_auto_20210205_1827'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trans_Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transferencia', models.FileField(upload_to='documents/%Y/%m/%d')),
            ],
            options={
                'verbose_name': 'Pagos de Trasferencia',
                'verbose_name_plural': 'Pagos de Trasferencia',
            },
        ),
        migrations.AlterModelOptions(
            name='check_payment',
            options={'ordering': ('-fecha_de_emision',), 'verbose_name': 'Pago con chequera', 'verbose_name_plural': 'Pagos con chequera'},
        ),
    ]
