# Generated by Django 3.1.5 on 2021-02-08 11:33

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ProFit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='admin_user',
            field=models.CharField(max_length=50, null=True, verbose_name='Nombre del Administrador'),
        ),
        migrations.AddField(
            model_name='profile',
            name='comunal',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Número de áreas comunales'),
        ),
        migrations.AddField(
            model_name='profile',
            name='direccion',
            field=models.CharField(max_length=50, null=True, verbose_name='Direccion del edificio'),
        ),
        migrations.AddField(
            model_name='profile',
            name='pisos',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Número de pisos'),
        ),
        migrations.AddField(
            model_name='profile',
            name='telefono',
            field=models.CharField(max_length=50, null=True, verbose_name='Número de contacto de administración'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Nombre del Edificio'),
        ),
    ]
