# Generated by Django 3.2.13 on 2022-05-27 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProFit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_user', models.CharField(max_length=50, null=True, verbose_name='Nombre del Administrador')),
                ('edificio', models.CharField(max_length=50, null=True, verbose_name='Edificio')),
                ('direccion', models.CharField(max_length=50, null=True, verbose_name='Direccion del edificio')),
            ],
        ),
    ]
