# Generated by Django 3.2.13 on 2022-05-27 03:17

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('ProFit', '0002_userrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrequest',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='userrequest',
            name='phonenumber',
            field=phone_field.models.PhoneField(blank=True, max_length=31, verbose_name='Telefono'),
        ),
    ]
