# Generated by Django 3.2.13 on 2022-05-29 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProFit', '0007_auto_20220528_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='edificio',
            field=models.CharField(max_length=50, null=True, verbose_name='Nombre del Edificio:'),
        ),
    ]
