# Generated by Django 3.1.5 on 2021-02-06 13:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cotizaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profit',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de solicitud'),
        ),
        migrations.AddField(
            model_name='profit',
            name='meet_date',
            field=models.DateTimeField(null=True, verbose_name='Fije su cita de inspección técnica'),
        ),
        migrations.AddField(
            model_name='profit',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profit',
            name='Maintenance_type',
            field=models.CharField(choices=[('Correctivo', 'Correctivo'), ('Preventivo', 'Preventivo'), ('Revestimientos y Pintura', 'Revestimientos y Pintura'), ('Sistema de emergencia', 'Sistema de emergencia'), ('Remodelación', 'Remodelación'), ('Refacción', 'Refacción')], max_length=500, null=True, verbose_name='Maintenance Type'),
        ),
        migrations.AlterField(
            model_name='profit',
            name='activity',
            field=models.CharField(choices=[('Albañilería', 'Albañilería'), ('Plomería', 'Plomería'), ('Electricidad', 'Electricidad'), ('Hidráulica', 'Hidráulica'), ('Electromecánica', 'Electromecánica'), ('Luminaria', 'Luminaria')], max_length=500, null=True, verbose_name='Activity'),
        ),
    ]
