# Generated by Django 3.1.5 on 2021-02-07 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0002_auto_20210206_1337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profit',
            name='meet_date',
        ),
    ]
