# Generated by Django 3.1.5 on 2021-02-07 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0003_remove_profit_meet_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profit',
            options={'ordering': ('-activity',), 'verbose_name': 'Solicitud de Contizacion ProFit', 'verbose_name_plural': 'Solicitudes de Cotizaciones ProFits'},
        ),
        migrations.AddField(
            model_name='profit',
            name='Maintenance_Zone',
            field=models.CharField(choices=[('Bombas de agua', 'Bombas de agua'), ('Calderos', 'Calderos'), ('Generadores Eléctricos', 'Generadores Eléctricos'), ('Ingresos', 'Ingresos'), ('Parqueaderos', 'Parqueaderos'), ('Ascensores', 'Ascensores'), ('Area comunal', 'Area Comunal'), ('Departamento particular', 'Departamento particular'), ('Terraza', 'Terraza')], max_length=500, null=True, verbose_name='Maintenance Zone'),
        ),
        migrations.AlterField(
            model_name='profit',
            name='activity',
            field=models.CharField(choices=[('Albañilería', 'Albañilería'), ('Plomería', 'Plomería'), ('Electricidad', 'Electricidad'), ('Hidráulica', 'Hidráulica'), ('Electromecánica', 'Electromecánica'), ('Luminaria', 'Luminaria'), ('Limpieza y Desinfección', 'Limpieza y Desinfección')], max_length=500, null=True, verbose_name='Activity'),
        ),
    ]
