# Generated by Django 3.2.13 on 2022-08-29 22:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0013_user_following'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('edificio_0', '0002_auto_20220829_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coti_order',
            name='building_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='building', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='coti_order',
            name='user_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
