# Generated by Django 3.2.13 on 2022-08-29 23:54

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edificio_0', '0003_auto_20220829_1713'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project_Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_code', models.CharField(choices=[('PMC', 'PMC'), ('PMP', 'PMP'), ('PSE', 'PSE'), ('PSR', 'PSR')], max_length=3, null=True)),
                ('slug', models.SlugField(max_length=200, null=True)),
                ('email', models.EmailField(max_length=254, verbose_name='Correo Electrónico')),
                ('RUC2', models.CharField(max_length=100, verbose_name='RUC')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('aprobe', models.BooleanField(default=True)),
                ('price1', models.DecimalField(decimal_places=2, max_digits=1000, null=True, verbose_name='Valor total de proyectos')),
                ('price2', models.DecimalField(decimal_places=2, max_digits=10000, null=True, verbose_name='Valor de anticipo de proyectos')),
                ('price3', models.DecimalField(decimal_places=2, max_digits=10000, null=True, verbose_name='Valor de pendiente de proyectos')),
                ('dias', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(300)])),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('Iva2', models.PositiveSmallIntegerField(default=12)),
                ('code', models.CharField(blank=True, max_length=1000000)),
            ],
            options={
                'verbose_name': 'Proyectos',
                'verbose_name_plural': 'Proyectos',
                'ordering': ('-created',),
                'index_together': {('id', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='Project_OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price1', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('anticipo', models.PositiveIntegerField(default=50, verbose_name='anticipo')),
                ('paid', models.BooleanField(default=False)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='edificio_0.coti_order')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='edificio_0.project_order')),
            ],
        ),
    ]
