# Generated by Django 3.2.13 on 2022-08-30 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edificio_0', '0005_project_order_anticipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='coti_order',
            name='anticipo',
            field=models.PositiveIntegerField(default=50, null=True, verbose_name='Anticipo'),
        ),
    ]
