# Generated by Django 3.2.13 on 2022-08-30 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edificio_0', '0006_coti_order_anticipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coti_order',
            name='anticipo',
        ),
    ]
