# Generated by Django 3.2.13 on 2022-08-30 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edificio_0', '0007_remove_coti_order_anticipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cotizacion',
            name='anticipo',
        ),
    ]
