# Generated by Django 3.2.13 on 2022-06-06 18:10

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Mantenimiento Correctivo', 'MC'), ('Mantenimiento Preventivo', 'MP')], db_index=True, max_length=200, verbose_name='Tipo de mantenimiento')),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'Categoria de Mantenimiento',
                'verbose_name_plural': 'Categorias de Mantenimientos',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coti_code', models.CharField(choices=[('CMC', 'CMC'), ('CMP', 'CMP'), ('CSE', 'CSE'), ('CSR', 'CSR')], max_length=3, null=True)),
                ('name', models.CharField(blank=True, db_index=True, max_length=1000000, null=True, verbose_name='Nombre de Proyecto')),
                ('slug', models.SlugField(max_length=200, null=True)),
                ('item', models.CharField(blank=True, max_length=1000)),
                ('description', models.CharField(blank=True, max_length=1000000, null=True)),
                ('Units', models.CharField(choices=[('mL', 'ml'), ('m^2', 'm^2'), ('Kg', 'Kg'), ('Gl', 'Gl')], max_length=3, null=True)),
                ('image', models.ImageField(blank=True, upload_to='image_item/%Y/%m/%d', verbose_name='Imagenes Reportadas')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('available', models.BooleanField(default=True, verbose_name='Disponible')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Valor Unitario')),
                ('iva', models.IntegerField(default=12, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('quantity', models.PositiveIntegerField(default=1, null=True)),
                ('discount', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('code', models.CharField(blank=True, max_length=1000000)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='edificio_2.category', verbose_name='Categoria de Mantenimiento')),
            ],
            options={
                'verbose_name': 'la Cotización de Proyectos',
                'verbose_name_plural': 'Cotización de Proyectos',
                'ordering': ('-created',),
                'index_together': {('id', 'slug')},
            },
        ),
    ]
