# Generated by Django 3.2.13 on 2022-06-16 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edificio_2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='anticipo',
            field=models.PositiveIntegerField(default=50, null=True, verbose_name='Anticipo'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='updated_a',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de última actualización de anticipo'),
        ),
    ]
