# Generated by Django 3.2.13 on 2022-07-02 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edificio_2', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project_orderitem',
            old_name='price',
            new_name='price1',
        ),
        migrations.RemoveField(
            model_name='project_order',
            name='price1',
        ),
        migrations.RemoveField(
            model_name='project_order',
            name='price2',
        ),
        migrations.RemoveField(
            model_name='project_order',
            name='price3',
        ),
        migrations.AddField(
            model_name='coti_order',
            name='price1',
            field=models.DecimalField(decimal_places=2, max_digits=1000, null=True),
        ),
        migrations.AlterField(
            model_name='coti_order',
            name='price2',
            field=models.DecimalField(decimal_places=2, max_digits=10000, null=True),
        ),
        migrations.AlterField(
            model_name='coti_order',
            name='price3',
            field=models.DecimalField(decimal_places=2, max_digits=10000, null=True),
        ),
    ]
