# Generated by Django 3.2.13 on 2022-07-02 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edificio_2', '0002_auto_20220702_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coti_order',
            name='price1',
            field=models.DecimalField(decimal_places=2, max_digits=1000, null=True, verbose_name='Valor total de Cotización'),
        ),
    ]
