# Generated by Django 3.2.13 on 2022-06-16 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edificio_2', '0002_auto_20220616_1857'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coti_Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo Electrónico')),
                ('RUC2', models.CharField(max_length=100, verbose_name='RUC')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('aprobe', models.BooleanField(default=True)),
                ('Iva2', models.PositiveSmallIntegerField(default=12)),
                ('coti', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='edificio_2.cotizacion')),
            ],
            options={
                'verbose_name': 'Orden de Compra',
                'verbose_name_plural': 'Ordenes de Compras',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Coti_OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('anticipo', models.PositiveIntegerField(default=50, verbose_name='anticipo')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='edificio_2.cotizacion')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='edificio_2.coti_order')),
            ],
        ),
    ]
