# Generated by Django 3.2.13 on 2022-07-05 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edificio_2', '0004_alter_coti_order_aprobe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coti_order',
            name='RUC2',
            field=models.CharField(max_length=100, verbose_name='Escriba su C.I o RUC'),
        ),
        migrations.AlterField(
            model_name='coti_order',
            name='aprobe',
            field=models.BooleanField(default=False, verbose_name='Hacer click en el recueadro para verificar aprobación'),
        ),
        migrations.AlterField(
            model_name='coti_order',
            name='coti_code',
            field=models.CharField(choices=[('CMC', 'CMC'), ('CMP', 'CMP'), ('CSE', 'CSE'), ('CSR', 'CSR')], max_length=3, null=True, verbose_name='Elija el codigo de cotización'),
        ),
        migrations.AlterField(
            model_name='coti_order',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Escriba su correo electrónico'),
        ),
    ]
