# Generated by Django 3.2.13 on 2022-06-20 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edificio_2', '0004_coti_order_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='coti_order',
            name='code',
            field=models.CharField(blank=True, max_length=1000000),
        ),
        migrations.AddField(
            model_name='coti_order',
            name='coti_code',
            field=models.CharField(choices=[('CMC', 'CMC'), ('CMP', 'CMP'), ('CSE', 'CSE'), ('CSR', 'CSR')], max_length=3, null=True),
        ),
    ]
