# Generated by Django 3.2.13 on 2022-06-24 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0013_user_following'),
        ('edificio_2', '0005_auto_20220620_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='coti_order',
            name='building_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.group'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('Correctivo', 'MC'), ('Preventivo', 'MP')], db_index=True, max_length=200, verbose_name='Tipo de mantenimiento'),
        ),
    ]
