# Generated by Django 3.2.13 on 2022-07-12 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edificio_2', '0005_auto_20220705_1718'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paytrans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comprobante', models.ImageField(blank=True, upload_to='users/%Y/%m/%d/', verbose_name='Subir su comprobante')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor final de comprobante')),
            ],
        ),
    ]
