# Generated by Django 3.2.13 on 2022-07-12 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edificio_2', '0006_paytrans'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_orderitem',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
