# Generated by Django 3.2.13 on 2022-06-24 03:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('edificio_2', '0006_auto_20220624_0245'),
    ]

    operations = [
        migrations.AddField(
            model_name='coti_order',
            name='user_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
