# Generated by Django 3.2.13 on 2022-07-12 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edificio_2', '0007_project_orderitem_paid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paycheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cheque', models.ImageField(blank=True, upload_to='users/%Y/%m/%d/', verbose_name='Subir fotografia del cheque')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor final de comprobante')),
            ],
        ),
        migrations.AddField(
            model_name='project_order',
            name='price1',
            field=models.DecimalField(decimal_places=2, max_digits=1000, null=True, verbose_name='Valor total de proyectos'),
        ),
        migrations.AddField(
            model_name='project_order',
            name='price2',
            field=models.DecimalField(decimal_places=2, max_digits=10000, null=True, verbose_name='Valor de anticipo de proyectos'),
        ),
        migrations.AddField(
            model_name='project_order',
            name='price3',
            field=models.DecimalField(decimal_places=2, max_digits=10000, null=True, verbose_name='Valor de pendiente de proyectos'),
        ),
    ]
