# Generated by Django 3.2.13 on 2022-06-24 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edificio_2', '0008_coti_order_dias'),
    ]

    operations = [
        migrations.AddField(
            model_name='coti_order',
            name='slug',
            field=models.SlugField(max_length=200, null=True),
        ),
        migrations.AlterIndexTogether(
            name='coti_order',
            index_together={('id', 'slug')},
        ),
    ]
