# Generated by Django 3.2.13 on 2022-08-29 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edificio_2', '0009_auto_20220824_1240'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('-created',), 'verbose_name': 'Proyectos', 'verbose_name_plural': 'Proyectos'},
        ),
    ]
