# Generated by Django 3.2.13 on 2022-08-29 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edificio_2', '0010_alter_project_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project_order',
            name='proc',
        ),
        migrations.AlterField(
            model_name='project_orderitem',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='edificio_2.coti_order'),
        ),
        migrations.DeleteModel(
            name='project',
        ),
    ]
