# Generated by Django 3.0.5 on 2021-01-17 01:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import parler.fields
import parler.models
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Proyectos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coti_code', models.CharField(choices=[('CMC', 'CMC'), ('CMP', 'CMP'), ('CSE', 'CSE'), ('CSR', 'CSR')], max_length=3, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('dire', models.CharField(max_length=200, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('paid', models.BooleanField(default=False, verbose_name='Aprobado')),
                ('paid2', models.BooleanField(default=False, verbose_name='Rechazado')),
                ('iva', models.IntegerField(default=12, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('discount', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('code', models.CharField(blank=True, max_length=1000000)),
            ],
            options={
                'verbose_name': 'la Cotización de Proyectos',
                'verbose_name_plural': 'Cotización de Proyectos',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Diagnostico de Mantenimiento',
                'verbose_name_plural': 'Diagnostico de Mantenimiento',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Edificios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aprobar', models.BooleanField(null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Facturacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Notas de Egreso Home Detail',
                'verbose_name_plural': 'Notas de Egreso Home Detail',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=3, null=True, verbose_name='Codigo de Proyecto')),
                ('invoice_code', models.CharField(max_length=3, null=True, verbose_name='Codigo de Cotización')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de Creación')),
                ('Fecha', models.DateField(null=True, verbose_name='Fecha de entrega de Proyecto')),
                ('porcet2', models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Avance de Obra %')),
                ('porcet', models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Porcetanje de Anticipo %')),
                ('value2', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Valor neto de la cotización')),
                ('value3', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('value4', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'verbose_name': 'Seguimiento de Proyecto',
                'verbose_name_plural': 'Seguimiento de Proyecto',
            },
        ),
        migrations.CreateModel(
            name='PlandeTrabajo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=2, null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('total', models.DateTimeField(null=True)),
                ('project2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items3', to='Proyectos.Project')),
            ],
            options={
                'verbose_name': 'Plan de Trabajo',
                'verbose_name_plural': 'Planes de Trabajo',
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('Unit', models.CharField(choices=[('mL', 'ml'), ('m^2', 'm^2'), ('Kg', 'Kg'), ('Gl', 'Gl')], max_length=3, null=True)),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='HOMEDETAIL.Cotizacion')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_items', to='Proyectos.Project')),
            ],
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='Edificio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='HOMEDETAIL.Edificios', verbose_name='Edificios HomeDetail'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='project_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project', to='Proyectos.Project'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='report_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project', to='HOMEDETAIL.Diagnostico'),
        ),
        migrations.CreateModel(
            name='Analitycs2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=2, null=True)),
                ('price2', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ProTools Materials Price')),
                ('porce2', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='feed Protools Materials')),
                ('total1', models.CharField(max_length=2, null=True)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items2', to='HOMEDETAIL.Proyecto')),
            ],
            options={
                'verbose_name': 'Análisis de Costo Materiales',
                'verbose_name_plural': 'Análisis de Costos Materiales',
            },
        ),
        migrations.CreateModel(
            name='Analitycs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=2, null=True)),
                ('price1', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Promain workhand Price')),
                ('porce', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='feed Promain WorkHand')),
                ('total2', models.CharField(max_length=2, null=True)),
                ('projectPM', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='HOMEDETAIL.Proyecto')),
            ],
            options={
                'verbose_name': 'Análisis de Costo Mano de Obra',
                'verbose_name_plural': 'Análisis de Costos Mano de Obra',
            },
        ),
        migrations.CreateModel(
            name='ProyectosHomeDetail',
            fields=[
            ],
            options={
                'verbose_name': 'Seguimiento de Proyecto',
                'verbose_name_plural': 'Seguimiento de Proyecto',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('HOMEDETAIL.proyecto',),
        ),
        migrations.CreateModel(
            name='FacturacionTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('Egreso_num', models.CharField(max_length=200, null=True, verbose_name='Numero de Egreso')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date report Created')),
                ('EgresoHD', models.FileField(upload_to='Egreso_HomeDetail/')),
                ('numero_cheque', models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='NUmeracion de cheque')),
                ('banco', models.CharField(choices=[('Pichincha', 'Pichincha'), ('Produbanco', 'Produbanco'), ('Banco de Guayaquil', 'Banco de Guayaquil'), ('Banco Internacional', 'Banco Internacional')], max_length=55, null=True, verbose_name='Entidad Bancaria')),
                ('Aprobado', models.BooleanField(default=False)),
                ('Anuluado', models.BooleanField(default=False)),
                ('Edificio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Edificios2', to='HOMEDETAIL.Edificios', verbose_name='Edificios HomeDetail')),
                ('cotizacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='HOMEDETAIL.Cotizacion')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='HOMEDETAIL.Facturacion')),
                ('project_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projectName', to='Proyectos.Project')),
            ],
            options={
                'verbose_name': 'Notas de Egreso Home Detail Translation',
                'db_table': 'HOMEDETAIL_facturacion_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='EdificiosTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('building_code', models.CharField(choices=[('PFE', 'PFE'), ('PFC', 'PFC'), ('PFU', 'PFU'), ('PFS', 'PFS'), ('PFP', 'PFP')], max_length=3, verbose_name='Building Code')),
                ('building_id', models.CharField(max_length=500, verbose_name='Building ID')),
                ('building_name', models.CharField(help_text='Escribir el nombre del edificio', max_length=50, verbose_name='Building name')),
                ('city', models.CharField(max_length=100, verbose_name='city')),
                ('building_levels', models.IntegerField(default=0, null=True, validators=[django.core.validators.MaxValueValidator(99)])),
                ('building_address', models.CharField(max_length=250, verbose_name='Building address')),
                ('building_ruc', models.PositiveIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(999999999999999)])),
                ('building_accountant', models.CharField(max_length=20, verbose_name='Building Accountant ')),
                ('insurance_carrier', models.CharField(max_length=20, verbose_name='Building insurance carrier ')),
                ('administration_manager', models.CharField(max_length=20, verbose_name='administration manager name')),
                ('manager_administrator_name', models.CharField(max_length=50, verbose_name='Manager administrator name')),
                ('administrator_email', models.EmailField(max_length=254, verbose_name='administrator e-mail')),
                ('administrator_phonenumber', phone_field.models.PhoneField(blank=True, max_length=31, verbose_name='administrator phonenumber')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('code', models.CharField(blank=True, max_length=50, verbose_name='codigo')),
                ('project_number', models.CharField(blank=True, max_length=50, verbose_name='Projects Numbers')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='HOMEDETAIL.Edificios')),
            ],
            options={
                'verbose_name': 'edificios Translation',
                'db_table': 'HOMEDETAIL_edificios_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='DiagnosticoTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('report_code', models.CharField(choices=[('RMC', 'RMC'), ('RMP', 'RMP'), ('RSE', 'RSE'), ('RSR', 'RSR')], max_length=3, verbose_name='Report Code')),
                ('report_id', models.CharField(max_length=2, verbose_name='Report ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date report Created')),
                ('date_meet', models.DateTimeField(null=True, verbose_name='Date Technical meet')),
                ('project_name2', models.CharField(help_text='Escribir Nombre de Proyecto', max_length=50, verbose_name='Project name')),
                ('item_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='item Name')),
                ('item_description', models.TextField(blank=True, null=True, verbose_name='Item description')),
                ('image_item', models.ImageField(blank=True, null=True, upload_to='static/edificios/', verbose_name='image Item')),
                ('item_name2', models.CharField(blank=True, max_length=20, null=True, verbose_name='item Name')),
                ('item_description2', models.TextField(blank=True, null=True, verbose_name='Item description')),
                ('image_item2', models.ImageField(blank=True, null=True, upload_to='static/edificios/', verbose_name='image Item')),
                ('item_name3', models.CharField(blank=True, max_length=20, null=True, verbose_name='item Name')),
                ('item_description3', models.TextField(blank=True, null=True, verbose_name='Item description')),
                ('image_item3', models.ImageField(blank=True, null=True, upload_to='static/edificios/', verbose_name='image Item')),
                ('promain_code', models.CharField(help_text='Codigo de Tecnico Profix Responsable', max_length=20, verbose_name='ProMain Code')),
                ('dayswork', models.IntegerField(default=0, null=True, validators=[django.core.validators.MaxValueValidator(15)], verbose_name='Calendary days')),
                ('code', models.CharField(blank=True, max_length=10, verbose_name='codigo')),
                ('Edificio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Edificios3', to='HOMEDETAIL.Edificios', verbose_name='Edificios HomeDetail')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='HOMEDETAIL.Diagnostico')),
            ],
            options={
                'verbose_name': 'Diagnostico de Mantenimiento Translation',
                'db_table': 'HOMEDETAIL_diagnostico_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
