# Generated by Django 3.1.5 on 2021-02-09 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HOMEDETAIL', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnosticotranslation',
            name='Edificio',
        ),
    ]
