# Generated by Django 3.1.5 on 2021-02-09 16:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('HOMEDETAIL', '0004_remove_cotizacion_edificio'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='Edificio',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
