# Generated by Django 3.1.5 on 2021-02-04 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Proyectos', '0003_project_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='user',
        ),
    ]
