# Generated by Django 3.1.5 on 2021-02-11 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HOMEDETAIL', '0005_cotizacion_edificio'),
        ('Proyectos', '0006_auto_20210204_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='coti2',
            field=models.ManyToManyField(to='HOMEDETAIL.Cotizacion'),
        ),
    ]
