# Generated by Django 3.1.5 on 2021-02-11 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Proyectos', '0007_project_coti2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='coti2',
        ),
    ]
