# Generated by Django 3.1.5 on 2021-02-19 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProFit', '0004_auto_20210208_1214'),
        ('Proyectos', '0008_remove_project_coti2'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='direccion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ProFit.profile'),
        ),
    ]
