# Generated by Django 3.1.5 on 2021-02-28 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proyectos', '0009_project_direccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='units',
            field=models.CharField(choices=[('m2', 'm2'), ('m3', 'm3'), ('ml', 'ml'), ('Gl', 'Gl')], db_index=True, max_length=200, null=True, verbose_name='Unidades'),
        ),
        migrations.AlterField(
            model_name='project',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Cantidad'),
        ),
    ]
