# Generated by Django 3.1.5 on 2021-03-05 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proyectos', '0011_project_anticipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='updated_a',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de última actualización de anticipo'),
        ),
    ]
